# Copyright © 2024 Beman Project
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Linux Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
  pull_request:
    branches: [ "main" ]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer: [ none asan ]
    steps:
      - uses: actions/checkout@v4
      - name: Linux ${{ matrix.sanitizer }}
        run: make ${{ matrix.sanitizer }}
