# Copyright © 2024 Beman Project
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Linux Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
  pull_request:
    branches: [ "main" ]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - id: linux-gcc-warnings
            cxx: g++
            name: warn
          - id: linux-gcc-warnings
            cxx: clang++
            name: warn
          - id: linux-gcc-asan
            cxx: g++
            name: asan
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.config.id }}
        run: make CXX=${{ matrix.config.cxx }} ${{ matrix.config.name }}
