# .github/workflows/macos.yml
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Macos Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-15
    strategy:
      fail-fast: false

      matrix:
        preset: [debug, release]
        # TODO: compiler: [g++-15, clang++-19]
        compiler: [clang++-19]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Cpp
        # if: startsWith(matrix.compiler, 'clang')
        uses: aminya/setup-cpp@v1
        with:
          ninja: true

      - name: Install llvm-19
        if: startsWith(matrix.compiler, 'clang')
        run: |
          brew install llvm@19 || echo ignored

      - name: macos clang++-19 ${{ matrix.preset }}
        if: startsWith(matrix.compiler, 'clang')
        run: CXX=$(brew --prefix llvm@19)/bin/clang++ cmake --workflow --preset ${{ matrix.preset }}

      - name: macos clang++-19 sanitizer
        if: startsWith(matrix.compiler, 'clang') && startsWith(matrix.preset, 'debug')
        run: CXX=$(brew --prefix llvm@19)/bin/clang++ make all

      - name: macos g++ ${{ matrix.preset }}
        if: startsWith(matrix.compiler, 'g++')
        run: CXX=${{ matrix.compiler }} cmake --workflow --preset ${{ matrix.preset }}

      # TODO: fails with AppleClang 16.0.0 on CI!
      # - name: macos g++ sanitizer
      #   if: startsWith(matrix.compiler, 'g++') && startsWith(matrix.preset, 'debug')
      #   run: CXX=${{ matrix.compiler }} make all
